### ISSUE TITLE
Getting a syntax error when i run it what did i do wrong

### ISSUE THREAD

**Issue by devinJanzen** [hermesdj/youtube-auto-processor#12]
> Executing task: npm run dev:electron <

> youtube-auto-processor@1.5.0 dev:electron
> quasar dev -m electron

 Dev mode.......... electron
 Pkg quasar........ v1.16.0 
 Pkg @quasar/app... v3.2.3  
 Pkg webpack....... v5      
 Debugging......... enabled 

 Configured browser support (>= 89.41% of global marketshare):
 · Chrome for Android >= 95
 · Firefox for Android >= 92
 · Android >= 95
 · Chrome >= 87
 · Edge >= 92
 · Firefox >= 85
 · iOS >= 11.3-11.4
 · Opera >= 77
 · Safari >= 12.1

undefined:1
undefined
^

[  SyntaxError: Unexpected token u in JSON at position 0

  - JSON.parse

  - quasar-conf-file.js:30 clone
    [youtube-auto-processor]/[@quasar]/app/lib/quasar-conf-file.js:30:15

  - quasar-conf-file.js:403 QuasarConfFile.compile
    [youtube-auto-processor]/[@quasar]/app/lib/quasar-conf-file.js:403:29

  - task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5

  - quasar-dev:240 async goLive
    [youtube-auto-processor]/[@quasar]/app/bin/quasar-dev:240:3

]

is what I get when I try to run it what did I do wrong

**Comment by it4mag** [comment]
Try running it with "quasar dev -m electron" ?
It is what I use.

**Comment by hermesdj** [comment]
Try running it with "quasar dev -m electron" ?
It is what I use.
