### ISSUE TITLE
Add parameter to "crop" videos at the beginning and the end

### ISSUE THREAD

**Issue by FabienDeshayes** [hermesdj/youtube-auto-processor#2]
I record with only one screen, which means that between the time I press "Start Recording" in OBS and the moment I start talking, I need a couple of seconds to `alt+tab` and get the game "up".

I'd like to add a parameter, probably in `youtube.json`, where I can specify a number of seconds to crop from the main recording. Would default to `0`.

**Comment by hermesdj** [comment]
I think it would be a good idea if by default it does not impact the current way it is working I don't see why you couldn't add this improvements ;)

**Comment by FabienDeshayes** [comment]
After investigation, to do this would need to be a two steps processing:
- transcode the "content" and crop the beginning and end
- concat the files

Trying to do it in one go, it seems that ffmpeg (or the node wrapper) will not support it.

So obviously not a good solution because:
* it adds complexity
* it will almost double the time

I'm looking at alternatives on my side.

**Comment by hermesdj** [comment]
On my side, I am using Keyboard Shortcuts to start and stop the recording.

**Comment by FabienDeshayes** [comment]
Yeah that's actually much better. I've tried it and it works nicely. Thanks!
